services:

  pg:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-six-city}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - six-city-network

  six-city-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    command: sh -c "npm install && npm run migration:run && npm start"
    networks:
      - six-city-network
    depends_on:
      - pg

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8000:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always
    networks:
      - six-city-network

volumes:
  postgres_data:
  pgadmin:

networks:
  six-city-network:
    driver: bridge