services:
  six-city-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/six-city-backend
    command: sh -c "npm i && npm run migration:run && npm start"
    networks:
      - six-city-network

networks:
  six-city-network:
    driver: bridge