services:
  
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
  six-city-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - database:/usr/src/six-city-backend
    command: sh -c "npm install && npm start && npm migration:run"
    networks:
      - six-city-network
    depends_on:
      - database
  
  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8000:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always
    networks:
      - six-city-network
    depends_on:
      - database

volumes:
  database:
  pgadmin:

networks:
  six-city-network:
    driver: bridge